<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <script src="https://kit.fontawesome.com/d5c56409b7.js" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="css/style.css">
    <title>Minha Agenda</title>
</head>
<body id="body">
    <header>
        <div class="center">
            <h1><img src="img/logo-agenda.png" alt="logo-agenda"></h1>
           <a href="#">Adicionar contato</a>
            <div class="container_btn_ME">
                <label>
                    <span class="text">Tema escuro</span>
                    <div class="box_btn_ME">
                        <input type="checkbox" id="btn_dark_mode">
                        <span class="btn_ME"></span>
                    </div>
                </label>
            </div>
        </div>
    </header>

    <section class="tabela">
            <table>
                <thead>
                    <tr>
                        <th class="">Nome</th>
                        <th>Telefone</th>
                    </tr>
                </thead>
                <tbody>
                    <tr>
                        <td>
                            sergio
                        </td>
                        <td>
                            444444
                        </td>
                        <td>
                           <a class="ver" href="#"><i class="fas fa-eye"></i></a>
                        </td>
                        <td>
                           <a class="editar" href="#"><i class="fas fa-edit"></i></a>
                        </td>
                        <td>
                           <a class="excluir" href="#"><i class="fas fa-trash-alt"></i></a>
                        </td>
                    </tr>
                    <tr>
                        <td>
                            Luiz fernando enrique de castro oliveira junior
                        </td>
                        <td>
                           (11) 94545-9642
                        </td>
                        <td>
                           <a class="ver" href="#"><i class="fas fa-eye"></i></a>
                        </td>
                        <td>
                           <a class="editar" href="#"><i class="fas fa-edit"></i></a>
                        </td>
                        <td>
                           <a class="excluir" href="#"><i class="fas fa-trash-alt"></i></a>
                        </td>
                    </tr>
                </tbody>
            </table>
    </section>

    <script src="js/scripts.js"></script>
</body>
</html>